### PR TITLE
Improve standard tomo loader's handling of angles and darks/flats [WIP]

### PR DESCRIPTION
**Pull request by yousefmoazzam**
The two main features that this PR will add are:
- An `angles` parameter which can be used either to provide an alternative path within the NeXuS file that contains the rotation angles, or provide a python expression (either a list or a numpy expression) to define the angles manually
- The parameters `flats` and `darks`, which can be used to load darks/flats that are separate to the projection data (either in different datasets within the same NeXuS file as the projection data, or in a completely separate NeXuS/hdf file to the projection data)

### CODE REVIEW

**Comment by yousefmoazzam** [comment]
With the changes so far, httomo is now able to load the following data:

The I12 test data:
- projections: https://github.com/DiamondLightSource/Savu/blob/master/test_data/data/i12_test_data/i12_test_data.nxs
- darks: https://github.com/DiamondLightSource/Savu/blob/master/test_data/data/i12_test_data/dark_field.nxs01_savu.plugins.no_process_plugin_tomo.h5
- flats: https://github.com/DiamondLightSource/Savu/blob/master/test_data/data/i12_test_data/flat_field.nxs01_savu.plugins.no_process_plugin_tomo.h5

from the Savu repo https://github.com/DiamondLightSource/Savu/tree/master/test_data/data/i12_test_data, with this loader config:
```yaml
- httomo.data.hdf.loaders:
    standard_tomo:
      name: tomo
      data_path: /1-TempPlugin-tomo/data
      rotation_angles:
        user_defined:
          start_angle: 0
          stop_angle: 180
          angles_total: 724
      dimension: 1
      preview: [null, null, null]
      pad: 0
      darks:
        file:
        data_path: /1-NoProcessPlugin-tomo/data
      flats:
        file:
        data_path: /1-NoProcessPlugin-tomo/data
```

This DIAD data `/dls/k11/data/2022/mg32775-1/nexus/k11-18014.nxs`, with this loader config:
```yaml
- httomo.data.hdf.loaders:
    standard_tomo:
      name: tomo
      data_path: /entry/imaging/data
      image_key_path: /entry/instrument/imaging/image_key
      rotation_angles:
        data_path: /entry/imaging_sum/gts_theta_value
      dimension: 1
      preview:
        -
        - start: 900
          stop: 902
      pad: 0
```

This eBIC data `/dls/ebic/data/staff-scratch/K11/wet_samples/crbon_virgin_wet_1_0p008mVV_/crbon_virgin_wet_1_0p008mVV_.h5`, with the following loader config:
```yaml
- httomo.data.hdf.loaders:
    standard_tomo:
      name: tomo
      data_path: /exchange/data
      rotation_angles:
        data_path: /exchange/theta
      dimension: 1
      preview:
        -
        - start: 900
          stop: 903
      pad: 0
      darks:
        file: /dls/ebic/data/staff-scratch/K11/wet_samples/crbon_virgin_wet_1_0p008mVV_/crbon_virgin_wet_1_0p008mVV_.h5
        data_path: /exchange/data_dark
      flats:
        file: /dls/ebic/data/staff-scratch/K11/wet_samples/crbon_virgin_wet_1_0p008mVV_/crbon_virgin_wet_1_0p008mVV_.h5
        data_path: /exchange/data_white_post
```

**Comment by dkazanc** [comment]
great stuff, thanks @yousefmoazzam 
Could we also:
- Upload I12 test data to [testdata](https://github.com/DiamondLightSource/httomo/tree/main/testdata). 
- A test that runs httomo with an associated loader for the dataset. May be @namannimmo10 could help with that? 
- Could we downsample k11 and eBIC data to ~10MB datasize and upload it as well? Do we need a downsample plugin in _httomolib_ and a utility (in httomo?) that writes metadata into the resulting file from the input file? I guess we would need something like that for users anyway to downsample reconstruction results. 
- Make tests for them as well with the loaders provided.

**Comment by dkazanc** [comment]
thought about it a bit. With the nexus file separate we probably can simply copy the nexus and create the right key in the downsampled data. With the keys integrated into hdf5 file we need to copy them. Let me create a separate issue on that. So far let's just add i12 data and the associated test.

**Comment by dkazanc** [comment]
Added i12 data with separate flats/darks and also downsampled k11_diad data (tested, it works!). Will look at ebic tmr. 

@namannimmo10 would you please organise the tests for the loaders.

At this point we need to test that the runner with a loader has been executed without errors, but we will work on the dedicated saver and then we can run the proper test chain: load->save->test the validity of the saved data

So far we need to test the following:

- [ ]  [the standard tomo loader](https://github.com/DiamondLightSource/httomo/blob/improve-loader-params/samples/pipeline_template_examples/01_basic_cpu_pipeline_tomo_standard.yaml) can load the [standard data](https://github.com/DiamondLightSource/httomo/blob/improve-loader-params/testdata/tomo_standard.nxs). 
- [ ]  [k11 data ](https://github.com/DiamondLightSource/httomo/blob/improve-loader-params/testdata/k11_diad/k11-18014.nxs) can be loaded  with the [loader](https://github.com/DiamondLightSource/httomo/blob/improve-loader-params/samples/beamline_loader_configs/diad.yaml) 
- [ ] [i12 separate flats darks data](https://github.com/DiamondLightSource/httomo/tree/improve-loader-params/testdata/i12/separate_flats_darks) can be loaded with this [template](https://github.com/DiamondLightSource/httomo/blob/improve-loader-params/testdata/i12/separate_flats_darks/yaml_loader_template/loader_separate_flats_darks.yaml)

**Pull request merged**
