### PR TITLE
Refactor loading

### LINKED ISSUE #27: Code inconsistent with the docstring
See https://github.com/DiamondLightSource/HTTomo/blob/8b8e64f0a3c9ed8729052c196fef0fe8ace4cf89/src/httomo/data/hdf/loaders.py#L12

The docstring says, 

>     Returns
>     -------
>     Tuple[ndarray, ndarray, ndarray, ndarray, ndarray, int, int, int]
>         A tuple of 8 values that all loader functions return.

But the function actually returns a tuple having seven values.  This is one reason I believe Python should have strict type-checking--helps in reducing errors.

### PR DESCRIPTION
**Pull request by namannimmo10**
This is an attempt to refactor [`load.py`](https://github.com/DiamondLightSource/httomo/blob/main/httomo/data/hdf/_utils/load.py) & [`loaders.py`](https://github.com/DiamondLightSource/httomo/blob/main/httomo/data/hdf/loaders.py) and see if we get some speedups.
- [x] add tests for `load_data` before refactoring
- [x] add tests for `standard_tomo` from loaders.py before refactoring
- [x] merge `read_through_dim1`, `read_through_dim2`, `read_through_dim3` into one function
- [x] Improve the performance of `get_data_indices` function by using a vectorized implementation (avoid `for` loops, use `np.where` and finally return a list)
- [x] remove all occurrences of `round` from the file (used integer division `//` which is faster than using `/` + `round`)
- [ ] .. 

Fixes #27

### CODE REVIEW

**Comment by namannimmo10** [comment]
I have done initial profiling using `cProfile` for the `standard_tomo` loader function.

```python
import cProfile
import pstats
import time
from mpi4py import MPI

comm = MPI.COMM_WORLD

from httomo.data.hdf.loaders import standard_tomo


preview = [None, {"start": 5, "stop": 10}, None]
standard_data = "tests/test_data/tomo_standard.nxs"
standard_data_path = "entry1/tomo_entry/data/data"
standard_image_key_path = "/entry1/tomo_entry/instrument/detector/image_key"

globals_dict = {"standard_tomo": standard_tomo}

locals_dict = {
    "comm": comm,
    "preview": preview,
    "standard_data": standard_data,
    "standard_data_path": standard_data_path,
    "standard_image_key_path": standard_image_key_path,
}


start = time.time()
cProfile.runctx(
    "standard_tomo('tomo', standard_data, standard_data_path, 1, preview, 1, comm, image_key_path=standard_image_key_path)",
    globals=globals_dict,
    locals=locals_dict,
    filename="standard_tomo.stats",
)
print("TOTAL TIME TAKEN: ", time.time() - start, end="\n\n")

p = pstats.Stats("standard_tomo.stats")
p.sort_stats("cumulative").print_stats()
```


```python
$ python t.py
TOTAL TIME TAKEN:  10.544009685516357

Thu Apr 27 11:09:33 2023    standard_tomo.stats

         3721 function calls (3716 primitive calls) in 10.526 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000   10.526   10.526 {built-in method builtins.exec}
        1    0.000    0.000   10.526   10.526 <string>:1(<module>)
        1    0.000    0.000   10.526   10.526 /home/qfc83269/Applications/oss/httomo/httomo/data/hdf/loaders.py:12(standard_tomo)
      482    0.003    0.000    8.597    0.018 /dls/science/users/qfc83269/condaenvs/httomo_new/lib/python3.10/site-packages/h5py/_hl/dataset.py:749(__getitem__)
      482    8.592    0.018    8.592    0.018 {method 'read' of 'h5py._selector.Reader' objects}
      442    0.003    0.000    5.173    0.012 /dls/science/users/qfc83269/condaenvs/httomo_new/lib/python3.10/site-packages/h5py/_hl/dataset.py:712(__iter__)
        1    0.001    0.001    4.302    4.302 /home/qfc83269/Applications/oss/httomo/httomo/data/hdf/_utils/load.py:256(get_darks_flats_together)
        1    0.001    0.001    2.980    2.980 /home/qfc83269/Applications/oss/httomo/httomo/data/hdf/_utils/load.py:431(get_data_indices)
        1    0.000    0.000    2.351    2.351 /home/qfc83269/Applications/oss/httomo/httomo/data/hdf/_utils/load.py:12(load_data)
        1    0.000    0.000    2.351    2.351 /home/qfc83269/Applications/oss/httomo/httomo/data/hdf/_utils/load.py:52(read_through_dim)
        6    1.381    0.230    1.382    0.230 /dls/science/users/qfc83269/condaenvs/httomo_new/lib/python3.10/site-packages/h5py/_hl/group.py:348(__getitem__)
        2    0.000    0.000    1.310    0.655 /home/qfc83269/Applications/oss/httomo/httomo/data/hdf/_utils/load.py:369(_get_darks_flats)
        2    0.000    0.000    1.310    0.655 /home/qfc83269/Applications/oss/httomo/httomo/data/hdf/_utils/load.py:427(<listcomp>)
       11    0.000    0.000    0.540    0.049 /dls/science/users/qfc83269/condaenvs/httomo_new/lib/python3.10/site-packages/h5py/_hl/files.py:375(__init__)
        5    0.539    0.108    0.539    0.108 /dls/science/users/qfc83269/condaenvs/httomo_new/lib/python3.10/site-packages/h5py/_hl/files.py:211(make_fid)
        1    0.000    0.000    0.476    0.476 /home/qfc83269/Applications/oss/httomo/httomo/data/hdf/_utils/load.py:234(get_angles)
```

**Comment by namannimmo10** [comment]
With https://github.com/DiamondLightSource/httomo/pull/119/commits/a6f3b32cc032abcd11a4d2cb52b96e2929a04d93 you can run _slow_ tests separately with `pytest -m slow` and run the remaining (fast) tests with `pytest -m "not slow"`.

**Comment by dkazanc** [comment]
@namannimmo10 any idea what should we do with this PR? The loader have changed since then slightly so may be we could either update the changes accordingly?

**Comment by yousefmoazzam** [comment]
Just putting my two cents here.

As of #198 being merged, the `load.py` and `loaders.py` files are no longer used in httomo to provide "the standard tomo loader". They are kept in the repo for now largely due to not having all functionality from "the old loader" in the "new block loader" (see #211, #220, #221 for the main features still absent in the new loader), and not wanting to delete code until all cases have been covered in the new loader.

When creating the new block loader, various pieces were taken from this PR, like https://github.com/DiamondLightSource/httomo/blob/c2bc45ae3b9430703789ca4c60212c8464fbbbfb/httomo/darks_flats.py#L23-L24

taken from 93f4c11, and https://github.com/DiamondLightSource/httomo/blob/c2bc45ae3b9430703789ca4c60212c8464fbbbfb/httomo/preview.py#L61

taken from a0e5edb, so the new loader has some of the improved changes that were highlighted in this PR.

Given that it's not particularly useful to be updating the old loader that's no longer used/exposed as "standard tomo loader", and the non-trivial effort it would take to bring this PR up to date so that's it's somehow applying changes to the new block loader, I'd propose to:
- close this PR
- check if there is anything performance-wise which was highlighted here but is missing from the new loader; if so, make those changes in a new PR on a branch off of `main`

**Comment by namannimmo10** [comment]
Great insights, I will close this.

**Pull request closed without merging**
